### ISSUE TITLE
PyPI package pyodc-1.0.2 is missing CHANGELOG.rst

### ISSUE THREAD

**Issue by markjolah** [ecmwf/pyodc#3]
The tarball release of [pyodc-1.0.2 on PyPI](https://pypi.org/project/pyodc/#files) is missing the file `CHANGELOG.rst` which leads the the following failure to run setup.py.
```
python3.6 setup.py build -j 16
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    long_description=read('README.rst') + read('CHANGELOG.rst'),
  File "setup.py", line 10, in read
    return io.open(file_path, encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
```
However, the 1.0.2 tarball in the github releases tab does have the `CHANGELOG.rst`.

**Comment by thebaptiste** [comment]
Same problem for me.
You should add a MANIFEST.in file to include CHANGELOG.rst in the tarball release or do not use CHANGELOG.rst in setup.py

**Comment by floriankrb** [comment]
Version 1.1.0 still have this issue. I cannot install 1.1.0 with pip. Strangely 1.0.3 installs ok.

❯ pip install --user pyodc==1.1.0
Collecting pyodc==1.1.0
  Using cached pyodc-1.1.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /data/conda/condaenvs/test-pyodc/bin/python3.8 /data/conda/condaenvs/test-pyodc/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpq3v94mvx
       cwd: /tmp/pip-install-jaf_sayl/pyodc_479f806423d2446987d26482d5b2ebf7
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/data/conda/condaenvs/test-pyodc/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/data/conda/condaenvs/test-pyodc/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/data/conda/condaenvs/test-pyodc/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-e0c51356/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-e0c51356/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-e0c51356/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-e0c51356/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 27, in <module>
      long_description=read("README.md") + read("CHANGELOG.md"),
    File "setup.py", line 10, in read
      return io.open(file_path, encoding="utf-8").read()
  FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e7/bc/8db10ddcadb9dd552baf40543c3b0a74029684c5dbd3880d1e8114b6d4ab/pyodc-1.1.0.tar.gz#sha256=34fd83c5bdeea578a5d0efb1c51b459e6b8ddaf94cd26be2e11c72fb39b68a99 (from https://pypi.org/simple/pyodc/). Command errored out with exit status 1: /data/conda/condaenvs/test-pyodc/bin/python3.8 /data/conda/condaenvs/test-pyodc/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpq3v94mvx Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyodc==1.1.0 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0)
ERROR: No matching distribution found for pyodc==1.1.0

**Comment by thebaptiste** [comment]
Yes, there is now the same problem with CHANGELOG.md instead of CHANGELOG.rst

Maybe I am missing something but I wonder why such an easy problem to fix has still not been fixed for over a year...

The tarballs are ok (with CHANGELOG file included) on github, but not on pypi.

**Comment by dvuckovic** [comment]
Sorry for taking so long to respond. This has been fixed internally with 59c1163, the change will be synced to Github later in the afternoon. The fix will be shipped in 1.1.1 release, thanks for the report.

**Comment by simondsmart** [comment]
I'm closing this as it is now fixed. It will appear in the develop branch later this evening when synced with our internal repo.

**Comment by thebaptiste** [comment]
Thank you very much
